apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerapp
  labels:
    app.kubernetes.io/name: dockerapp
    app.kubernetes.io/instance: dockerapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dockerapp
      app.kubernetes.io/instance: dockerapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dockerapp
        app.kubernetes.io/instance: dockerapp
    spec:
      containers:
        - name: dockerapp
          image: raviaman9/dockerapp:v4
          ports:
            - containerPort: 8080
