apiVersion: v1
kind: Service
metadata:
  name: dockerapp
  labels:
    app.kubernetes.io/name: dockerapp
    app.kubernetes.io/instance: dockerapp
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: dockerapp
    app.kubernetes.io/instance: dockerapp
  ports:
    - port: 80
      targetPort: 8080
